name = "Molly"
uuid = "aa0f7f06-fcc0-5ec4-a7f3-a573f33f9c4c"
authors = ["Joe G Greener <jgreener@hotmail.co.uk>"]
version = "0.4.0"

[deps]
BioStructures = "de9282ab-8554-53be-b2d6-f6c222edabfc"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
BioStructures = "0.10, 0.11, 1"
CUDA = "3"
Colors = "0.10, 0.11, 0.12"
Distances = "0.10"
Distributions = "0.23, 0.24, 0.25"
KernelDensity = "0.5, 0.6"
NearestNeighbors = "0.4"
ProgressMeter = "1"
Reexport = "0.2, 1"
Requires = "1"
StaticArrays = "0.12, 1"
Unitful = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "GLMakie", "Statistics", "Test"]
