name = "Molly"
uuid = "aa0f7f06-fcc0-5ec4-a7f3-a573f33f9c4c"
authors = ["Joe G Greener <jgreener@hotmail.co.uk>"]
version = "0.14.3"

[deps]
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
BioStructures = "de9282ab-8554-53be-b2d6-f6c222edabfc"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CellListMap = "69e1c6dd-3888-40e6-b3c8-31ac5f578864"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Chemfiles = "46823bd8-5fb3-5f92-9aa0-96921f3dd015"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulChainRules = "f31437dd-25a7-4345-875f-756556e6935d"
UnsafeAtomicsLLVM = "d80eeb9a-aca5-4d75-85e5-170c8b632249"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Atomix = "0.1"
AtomsBase = "0.3"
BioStructures = "1, 2"
CUDA = "3, 4"
CellListMap = "0.8.11"
ChainRulesCore = "1"
Chemfiles = "0.10.3"
Colors = "0.10, 0.11, 0.12"
Combinatorics = "1"
DataStructures = "0.18"
Distances = "0.10"
Distributions = "0.23, 0.24, 0.25"
Enzyme = "0.11"
EzXML = "1"
FLoops = "0.2"
ForwardDiff = "0.10.35"
KernelDensity = "0.5, 0.6"
NearestNeighbors = "0.4"
Reexport = "1"
Requires = "1"
StaticArrays = "1.5.17"
Unitful = "1"
UnitfulChainRules = "= 0.1.2"
UnsafeAtomicsLLVM = "0.1"
Zygote = "0.6.56 - 0.6.60"
julia = "1.7"
